[build]
  publish = "dist"
  command = "npm install && npm run build"

[build.environment]
  NODE_VERSION = "18"
  NPM_CONFIG_FUND = "false"
  NPM_CONFIG_AUDIT = "false"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200