[build]
  publish = "dist"
  command = "rm -rf node_modules package-lock.json && npm install --force && npm run build"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--force --no-optional"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200